name: Deploy para Azure com Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Login no Azure com OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      - name: Terraform Apply
        run: |
          export TF_LOG=DEBUG
          export TF_LOG_PATH=terraform.log
          terraform apply -auto-approve -input=false
        working-directory: infra
        env:
          TF_VAR_container_registry_name: ${{ secrets.AZURE_ACR_NAME }}
          TF_VAR_acr_username: ${{ secrets.AZURE_ACR_USERNAME }}
          TF_VAR_acr_password: ${{ secrets.AZURE_ACR_PASSWORD }}
          TF_VAR_NEO4J_URI: ${{ secrets.NEO4J_URI }}
          TF_VAR_NEO4J_USER: ${{ secrets.NEO4J_USER }}
          TF_VAR_NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          TF_VAR_PORT: ${{ secrets.PORT }}
          TF_VAR_STORAGE_KEY_AZURE: ${{ secrets.STORAGE_KEY_AZURE }}
