name: Deploy para Azure com Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Login no Azure com OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      - name: Importar ambiente existente
        run: |
          terraform import azurerm_container_app_environment.env "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/genealogia-academica/providers/Microsoft.App/managedEnvironments/PROD"
        working-directory: infra

      - name: Terraform Apply
        run: |
          export TF_LOG=DEBUG
          export TF_LOG_PATH=terraform.log
          terraform apply -auto-approve -input=false
        working-directory: infra
        env:
          TF_VAR_container_registry_name: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          TF_VAR_acr_username: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_acr_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_NEO4J_URI: ${{ secrets.NEO4J_URI }}
          TF_VAR_NEO4J_USER: ${{ secrets.NEO4J_USER }}
          TF_VAR_NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          TF_VAR_PORT: ${{ secrets.PORT }}
          TF_VAR_STORAGE_KEY_AZURE: ${{ secrets.STORAGE_KEY_AZURE }}
          TF_VAR_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
